export interface SizeConfig {
  id: string;
  name: string;
  category: "browser" | "mobile" | "tv";
  width: number;
  height: number;
  showAvatar: boolean;
  showChannel: boolean;
  showViews: boolean;
  layout: "grid" | "row";
  description: string;
  readability: "optimal" | "moderate" | "critical";
  warningText: string;
}

export const sizeConfigs: SizeConfig[] = [
  // --- BROWSER ---
  {
    id: "browser-home-large",
    name: "Homepage Large",
    category: "browser",
    width: 360,
    height: 205,
    showAvatar: true,
    showChannel: true,
    showViews: true,
    layout: "grid",
    description: "Desktop browser homepage video card grid preview.",
    readability: "optimal",
    warningText: "Great readability. Standard styling and smaller text highlights are generally legible here.",
  },
  {
    id: "browser-home-small",
    name: "Homepage Small",
    category: "browser",
    width: 240,
    height: 135,
    showAvatar: true,
    showChannel: true,
    showViews: true,
    layout: "grid",
    description: "Desktop browser homepage compact grid card.",
    readability: "moderate",
    warningText: "Moderate readability. Avoid thin fonts; keep key overlay texts clear and centered.",
  },
  {
    id: "browser-sidebar-suggested",
    name: "Sidebar Suggested Video",
    category: "browser",
    width: 168,
    height: 94,
    showAvatar: false,
    showChannel: true,
    showViews: true,
    layout: "row",
    description: "Desktop sidebar watch page recommendation item.",
    readability: "critical",
    warningText: "Critical readability. Use high-contrast backgrounds and bold, large lettering only.",
  },
  {
    id: "browser-search-large",
    name: "Search Result Large",
    category: "browser",
    width: 360,
    height: 202,
    showAvatar: false,
    showChannel: true,
    showViews: true,
    layout: "row",
    description: "Desktop browser search results list item.",
    readability: "optimal",
    warningText: "Optimal thumbnail size. Fine details and sub-texts are visible to searchers.",
  },
  {
    id: "browser-search-small",
    name: "Search Result Small",
    category: "browser",
    width: 240,
    height: 135,
    showAvatar: false,
    showChannel: true,
    showViews: true,
    layout: "row",
    description: "Desktop search results page secondary list item.",
    readability: "moderate",
    warningText: "Moderate readability. Thumbnail text must be prominent to compete with adjacent search results.",
  },
  {
    id: "browser-channel-page",
    name: "Channel Page",
    category: "browser",
    width: 270,
    height: 150,
    showAvatar: false,
    showChannel: false,
    showViews: true,
    layout: "grid",
    description: "Desktop creator profile videos page grid card.",
    readability: "optimal",
    warningText: "Good readability. Focus on visual coherence with your channel theme here.",
  },
  {
    id: "browser-channel-page-small",
    name: "Channel Page Small",
    category: "browser",
    width: 198,
    height: 112,
    showAvatar: false,
    showChannel: false,
    showViews: true,
    layout: "grid",
    description: "Desktop creator profile compact grid item.",
    readability: "moderate",
    warningText: "Moderate readability. Smaller text elements might begin to blur for viewers.",
  },
  {
    id: "browser-watch-later",
    name: "Watch Later",
    category: "browser",
    width: 188,
    height: 106,
    showAvatar: true,
    showChannel: true,
    showViews: true,
    layout: "row",
    description: "Desktop Watch Later queue list row (540x106 px container).",
    readability: "critical",
    warningText: "Critical thumbnail scale. Limit words on the thumbnail; ensure excellent color separation.",
  },

  // --- MOBILE ---
  {
    id: "mobile-home",
    name: "Mobile Homepage",
    category: "mobile",
    width: 320,
    height: 180,
    showAvatar: true,
    showChannel: true,
    showViews: true,
    layout: "grid",
    description: "YouTube app mobile feed standard card.",
    readability: "optimal",
    warningText: "Good readability on high-DPI screens. Make sure visual focus is clear at arm's length.",
  },
  {
    id: "mobile-suggested",
    name: "Mobile Suggested",
    category: "mobile",
    width: 168,
    height: 94,
    showAvatar: false,
    showChannel: true,
    showViews: true,
    layout: "row",
    description: "Mobile watch page sidebar/suggested row card.",
    readability: "critical",
    warningText: "Critical scale. Keep graphics simple. Faces and primary objects should dominate.",
  },
  {
    id: "mobile-search",
    name: "Mobile Search",
    category: "mobile",
    width: 320,
    height: 180,
    showAvatar: true,
    showChannel: true,
    showViews: true,
    layout: "grid",
    description: "Mobile app search results page list card.",
    readability: "optimal",
    warningText: "Excellent layout width. Clear visuals will successfully draw attention in search feeds.",
  },

  // --- APPLE TV ---
  {
    id: "tv-home",
    name: "Homepage",
    category: "tv",
    width: 512,
    height: 288,
    showAvatar: true,
    showChannel: true,
    showViews: true,
    layout: "grid",
    description: "Apple TV YouTube app landing dashboard item.",
    readability: "optimal",
    warningText: "Outstanding size. Perfect for rich graphics. Text works great but should not look overcrowded.",
  },
  {
    id: "tv-recommended",
    name: "Apple TV Recommended",
    category: "tv",
    width: 512,
    height: 288,
    showAvatar: true,
    showChannel: true,
    showViews: true,
    layout: "grid",
    description: "Apple TV watch screen recommended shelf item.",
    readability: "optimal",
    warningText: "High visibility dashboard card. Maintain clean composition and saturated colors.",
  },
  {
    id: "tv-watch-later",
    name: "Watch Later",
    category: "tv",
    width: 360,
    height: 200,
    showAvatar: true,
    showChannel: true,
    showViews: true,
    layout: "grid",
    description: "Apple TV playlist library thumbnail card.",
    readability: "optimal",
    warningText: "Optimal scale. Looks great on TV displays. Contrast is key for viewer attention.",
  },
];

export const categories = [
  { id: "all", label: "All Devices", icon: "🌐" },
  { id: "browser", label: "Desktop Browser", icon: "🖥️" },
  { id: "mobile", label: "Mobile App", icon: "📱" },
  { id: "tv", label: "Apple TV YouTube", icon: "📺" },
] as const;
